module.exports = [
  {
    name: "battery1",
    capacity: 100,
    currentFilled: 50,
    cost: 0.3,
    serialNumber: "0x1",
    priceThreshold: 7e3,
    chargeRate: 4,
  },
  {
    name: "battery2",
    capacity: 110,
    currentFilled: 55,
    cost: 0.5,
    serialNumber: "0x2",
    priceThreshold: 10e3,
    chargeRate: 6,
  },
  {
    name: "battery3",
    capacity: 90,
    currentFilled: 42,
    cost: 0.4,
    serialNumber: "0x3",
    priceThreshold: 5e3,
    chargeRate: 8,
  },
  {
    name: "battery4",
    capacity: 80,
    currentFilled: 38,
    cost: 0.7,
    serialNumber: "0x4",
    priceThreshold: 4e3,
    chargeRate: 2,
  },
  {
    name: "battery5",
    capacity: 70,
    currentFilled: 46,
    cost: 0.1,
    serialNumber: "0x5",
    priceThreshold: 3e3,
    chargeRate: 3,
  },
];
