import Head from "next/head";
import Image from "next/image";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import styles from "../styles/Home.module.css";
import batteries from "./api/batteries";
import VirtualPowerPlantInstructions from "../components/VirtualPowerPlantInstructions";
import Title from "../components/Title";
import batteryInfo from "./api/batteries";
import BatteryCarousel from "../components/BatteryCarousel";

export default function Home() {
  const year = new Date().getFullYear();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container fluid>
          <Row>
            <Title />
          </Row>
          <VirtualPowerPlantInstructions />
          <BatteryCarousel batteries={batteryInfo} />
        </Container>
      </main>

      <footer className={styles.footer}>Yan Man. {year}</footer>
    </div>
  );
}
